---
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cli/
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w'
      - -X github.com/drewstinnett/labdoc/cli/cmd.date={{ .CommitTimestamp }}
      - -X github.com/drewstinnett/labdoc/cli/cmd.version={{ .Tag }}
      - -X github.com/drewstinnett/labdoc/cli/cmd.commit={{ .ShortCommit }}
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    binary: 'labdoc'
archives:
  - format: tar.gz
    name_template: 'labdoc-{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: macOS
checksum:
  name_template: 'labdoc-{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  skip: true

brews:
  - name: 'labdoc'
    tap:
      owner: drewstinnett
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    description: "Generate README from a template, with some handy GitLab data"
    homepage: "https://github.com/drewstinnett/labdoc"
    license: BSD-2-Clause
dockers:
- image_templates:
  - 'ghcr.io/drewstinnett/labdoc:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
- image_templates:
  - 'ghcr.io/drewstinnett/labdoc:{{ .Tag }}-arm64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64"
  goarch: arm64